<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <UserSecretsId>0815ab11-8344-4a24-b508-f012b6c6c0a1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.34.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SME.SERAp.Prova.Item.IoC\SME.SERAp.Prova.Item.IoC.csproj" />
  </ItemGroup>

</Project>
